services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        NEXT_PUBLIC_GOOGLE_MAPS_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_KEY}
    env_file:
      - .env.local
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped
