import { type Activity } from '@/db/schema';

export const MOCK_ACTIVITIES: Activity[] = [
  // --- THINGS TO DO ---
  {
    id: 1,
    googlePlaceId: "g-1",
    name: "Golden Gate Bridge",
    description: "The iconic orange-red suspension bridge. Great for photo spots and scenic views at sunset.",
    lat: 37.8199,
    lng: -122.4783,
    address: "Golden Gate Bridge, San Francisco, CA",
    category: "activity",
    averageDuration: 60,
    rating: 4.8,
    priceLevel: 0,
    imageUrl: "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?auto=format&fit=crop&w=800&q=80",
    openingHours: null,
    websiteUrl: "https://goldengate.org",
    city: "San Francisco"
  },
  {
    id: 2,
    googlePlaceId: "g-2",
    name: "SFMOMA",
    description: "Modern and contemporary art museum featuring world-class galleries and architecture.",
    lat: 37.7857,
    lng: -122.4011,
    address: "151 3rd St, San Francisco, CA",
    category: "activity",
    averageDuration: 120,
    rating: 4.6,
    priceLevel: 2,
    imageUrl: "https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=800&q=80",
    openingHours: null,
    websiteUrl: "https://sfmoma.org",
    city: "San Francisco",
  },
  {
    id: 3,
    googlePlaceId: "g-3",
    name: "Alcatraz Island",
    description: "Former federal prison reachable by ferry. A historical landmark with haunting stories.",
    lat: 37.8270,
    lng: -122.4230,
    address: "San Francisco Bay, CA",
    category: "activity",
    averageDuration: 180,
    rating: 4.7,
    priceLevel: 3,
    imageUrl: "https://images.unsplash.com/photo-1628156105030-977465355609?auto=format&fit=crop&w=800&q=80",
    openingHours: null,
    websiteUrl: null,
    city: "San Francisco",
  },
  // --- RESTAURANTS ---
  {
    id: 4,
    googlePlaceId: "g-4",
    name: "Swan Oyster Depot",
    description: "Legendary seafood counter serving fresh oysters and crab. A must-visit local spot.",
    lat: 37.7909,
    lng: -122.4209,
    address: "1517 Polk St, San Francisco, CA",
    category: "restaurant",
    averageDuration: 45,
    rating: 4.8,
    priceLevel: 2,
    imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=800&q=80",
    openingHours: null,
    websiteUrl: null,
    city: "San Francisco",
  },
  {
    id: 5,
    googlePlaceId: "g-5",
    name: "Gary Danko",
    description: "High-end fine dining with an elegant atmosphere and world-class tasting menus.",
    lat: 37.8058,
    lng: -122.4206,
    address: "800 North Point St, San Francisco, CA",
    category: "restaurant",
    averageDuration: 150,
    rating: 4.9,
    priceLevel: 4,
    imageUrl: "https://images.unsplash.com/photo-1550966842-2849a2230870?auto=format&fit=crop&w=800&q=80",
    openingHours: null,
    websiteUrl: "http://garydanko.com",
    city: "San Francisco",
  }
];